import XCTest
@testable import CoreModels

final class CoreModelsTests: XCTestCase {
    func testPendingRepeatItemRoundTrip() throws {
        let item = PendingRepeatItem(
            word: "ephemeral",
            expectedAnswer: "geçici",
            dueAtRoundIndex: 5,
            weight: 2
        )
        let data = try JSONEncoder().encode([item])
        let decoded = try JSONDecoder().decode([PendingRepeatItem].self, from: data)
        XCTAssertEqual(decoded, [item])
    }

    /// Eski istemcilerin yazdığı `kindRaw`sız JSON hâlâ decode edilebilmeli.
    func testPendingRepeatItemDecodesLegacyJSONWithoutKind() throws {
        let legacy = Data("""
        [{"word":"give up","expectedAnswer":"vazgeçmek","dueAtRoundIndex":4,"weight":2}]
        """.utf8)
        let decoded = try JSONDecoder().decode([PendingRepeatItem].self, from: legacy)
        XCTAssertEqual(decoded.count, 1)
        XCTAssertEqual(decoded[0].kind, .word)
        XCTAssertEqual(decoded[0].word, "give up")
    }

    func testPendingRepeatItemKindRoundTrip() throws {
        let item = PendingRepeatItem(
            word: "break the ice",
            expectedAnswer: "buzları eritmek",
            dueAtRoundIndex: 7,
            weight: 1,
            kindRaw: ContentKind.idiom.rawValue
        )
        let data = try JSONEncoder().encode(item)
        let decoded = try JSONDecoder().decode(PendingRepeatItem.self, from: data)
        XCTAssertEqual(decoded, item)
        XCTAssertEqual(decoded.kind, .idiom)
    }

    /// Eski snapshot'lardaki RoundSnapshot yeni anahtarlar olmadan decode edilir.
    func testRoundSnapshotDecodesLegacyJSONWithoutNewFields() throws {
        let legacy = Data("""
        {"index":0,"askerRoleRaw":"host","word":"abundant","expectedAnswer":"bol",
         "judgementRaw":"correct","pointsAwarded":0,"isRepeat":false}
        """.utf8)
        let decoded = try JSONDecoder().decode(MatchStateSnapshot.RoundSnapshot.self, from: legacy)
        XCTAssertNil(decoded.kindRaw)
        XCTAssertNil(decoded.formatRaw)
        XCTAssertNil(decoded.options)
    }

    func testMatchStatusEnum() {
        XCTAssertEqual(MatchStatus.allCases.count, 3)
    }

    // MARK: - Player isim yardımcıları

    func testAutoNameFormatAndDeterminism() {
        let name = Player.autoName(for: "001234.abcd")
        XCTAssertTrue(name.hasPrefix("Player-"))
        XCTAssertTrue(Player.isAutoGeneratedName(name))
        XCTAssertEqual(name, Player.autoName(for: "001234.abcd"))
    }

    func testIsAutoGeneratedNameDetectsPlaceholderOnly() {
        XCTAssertTrue(Player.isAutoGeneratedName("Player-0427"))
        XCTAssertFalse(Player.isAutoGeneratedName("Ramazan"))
        XCTAssertFalse(Player.isAutoGeneratedName("Player-Ali"))
        XCTAssertFalse(Player.isAutoGeneratedName("Player-42"))
    }

    func testIsRealName() {
        XCTAssertTrue(Player.isRealName("Ramazan"))
        XCTAssertFalse(Player.isRealName(""))
        XCTAssertFalse(Player.isRealName("   "))
        XCTAssertFalse(Player.isRealName("Player-0427"))
    }
}
