import XCTest
@testable import CoreModels

final class CoreModelsTests: XCTestCase {
    func testPendingRepeatItemRoundTrip() throws {
        let item = PendingRepeatItem(
            word: "ephemeral",
            expectedAnswer: "geçici",
            dueAtRoundIndex: 5,
            weight: 2
        )
        let data = try JSONEncoder().encode([item])
        let decoded = try JSONDecoder().decode([PendingRepeatItem].self, from: data)
        XCTAssertEqual(decoded, [item])
    }

    func testMatchStatusEnum() {
        XCTAssertEqual(MatchStatus.allCases.count, 3)
    }

    // MARK: - Player isim yardımcıları

    func testAutoNameFormatAndDeterminism() {
        let name = Player.autoName(for: "001234.abcd")
        XCTAssertTrue(name.hasPrefix("Player-"))
        XCTAssertTrue(Player.isAutoGeneratedName(name))
        XCTAssertEqual(name, Player.autoName(for: "001234.abcd"))
    }

    func testIsAutoGeneratedNameDetectsPlaceholderOnly() {
        XCTAssertTrue(Player.isAutoGeneratedName("Player-0427"))
        XCTAssertFalse(Player.isAutoGeneratedName("Ramazan"))
        XCTAssertFalse(Player.isAutoGeneratedName("Player-Ali"))
        XCTAssertFalse(Player.isAutoGeneratedName("Player-42"))
    }

    func testIsRealName() {
        XCTAssertTrue(Player.isRealName("Ramazan"))
        XCTAssertFalse(Player.isRealName(""))
        XCTAssertFalse(Player.isRealName("   "))
        XCTAssertFalse(Player.isRealName("Player-0427"))
    }
}
