import Foundation
import SwiftData
import CoreModels

public enum PlayerUpsert {
    /// Otomatik üretilen görünen adların ön eki. Apple ismi sonradan
    /// geldiğinde bu placeholder'ın gerçek isimle değiştirilebilmesi için kullanılır.
    static let autoNamePrefix = "Player-"

    /// `appleUserID` benzersiz olduğu için bu id ile mevcut bir Player varsa güncellenir;
    /// yoksa yeni Player oluşturulup context'e insert edilir.
    ///
    /// Görünen ad kuralı:
    /// - İlk girişte Apple bir isim verirse o kullanılır.
    /// - Apple isim vermezse `Player-XXXX` (kimliğe bağlı sabit 4 hane) atanır.
    /// - Apple ismi yalnızca İLK onayda gelir; eğer placeholder bir adla
    ///   kaydolduysak ve sonraki bir onayda gerçek isim gelirse, placeholder'ı
    ///   gerçek isimle yükseltiriz (kullanıcının elle değiştirdiği adı ezmeyiz).
    @discardableResult
    public static func upsert(
        appleUserID: String,
        displayName: String,
        in context: ModelContext
    ) throws -> Player {
        var descriptor = FetchDescriptor<Player>(
            predicate: #Predicate { $0.appleUserID == appleUserID }
        )
        descriptor.fetchLimit = 1

        let appleName = displayName.trimmingCharacters(in: .whitespacesAndNewlines)

        if let existing = try context.fetch(descriptor).first {
            // Apple gerçek bir isim verdiyse ve mevcut ad boş ya da otomatik
            // placeholder ise gerçek isimle güncelle.
            if !appleName.isEmpty,
               existing.displayName.isEmpty || isAutoGenerated(existing.displayName) {
                existing.displayName = appleName
                try context.save()
            }
            return existing
        }

        let resolvedName = appleName.isEmpty ? defaultDisplayName(for: appleUserID) : appleName
        let new = Player(
            appleUserID: appleUserID,
            displayName: resolvedName,
            avatarColor: stableAvatarIndex(for: appleUserID)
        )
        context.insert(new)
        try context.save()
        return new
    }

    public static func delete(appleUserID: String, in context: ModelContext) throws {
        var descriptor = FetchDescriptor<Player>(
            predicate: #Predicate { $0.appleUserID == appleUserID }
        )
        descriptor.fetchLimit = 1
        if let existing = try context.fetch(descriptor).first {
            context.delete(existing)
            try context.save()
        }
    }

    // MARK: - Helpers

    /// Apple isim vermediğinde: `Player-XXXX`. Sonek, kimliğe bağlı sabit
    /// 4 haneli sayı (aynı kullanıcı her cihazda aynı adı görür). Opak Apple
    /// kimliğini kesmek yerine sayısal türetme — çirkin karakter çıkmaz.
    static func defaultDisplayName(for appleUserID: String) -> String {
        let number = stableHash(appleUserID) % 10000
        return autoNamePrefix + String(format: "%04d", number)
    }

    /// Verilen adın otomatik üretilmiş bir placeholder olup olmadığı
    /// (`Player-1234` kalıbı). Kullanıcının elle koyduğu adları korur.
    static func isAutoGenerated(_ name: String) -> Bool {
        guard name.hasPrefix(autoNamePrefix) else { return false }
        let suffix = name.dropFirst(autoNamePrefix.count)
        return suffix.count == 4 && suffix.allSatisfy(\.isNumber)
    }

    static func stableAvatarIndex(for appleUserID: String) -> Int {
        stableHash(appleUserID) % 8
    }

    /// Deterministik djb2 hash — aynı kullanıcı her cihazda aynı sonuç.
    private static func stableHash(_ string: String) -> Int {
        var hash = 5381
        for byte in string.utf8 {
            hash = ((hash << 5) &+ hash) &+ Int(byte)
        }
        return abs(hash)
    }
}
