import Foundation
import SwiftData
import CoreModels

public enum PlayerUpsert {
    /// `appleUserID` benzersiz olduğu için bu id ile mevcut bir Player varsa güncellenir;
    /// yoksa yeni Player oluşturulup context'e insert edilir.
    ///
    /// Görünen ad kuralı:
    /// - İlk girişte Apple bir isim verirse o kullanılır.
    /// - Apple isim vermezse `Player-XXXX` (kimliğe bağlı sabit 4 hane) atanır.
    /// - Apple ismi yalnızca İLK onayda gelir; eğer placeholder bir adla
    ///   kaydolduysak ve sonraki bir onayda gerçek isim gelirse, placeholder'ı
    ///   gerçek isimle yükseltiriz (kullanıcının elle değiştirdiği adı ezmeyiz).
    @discardableResult
    public static func upsert(
        appleUserID: String,
        displayName: String,
        in context: ModelContext
    ) throws -> Player {
        var descriptor = FetchDescriptor<Player>(
            predicate: #Predicate { $0.appleUserID == appleUserID }
        )
        descriptor.fetchLimit = 1

        let appleName = displayName.trimmingCharacters(in: .whitespacesAndNewlines)

        if let existing = try context.fetch(descriptor).first {
            // Apple gerçek bir isim verdiyse ve mevcut ad boş ya da otomatik
            // placeholder ise gerçek isimle güncelle.
            if !appleName.isEmpty,
               existing.displayName.isEmpty || Player.isAutoGeneratedName(existing.displayName) {
                existing.displayName = appleName
                try context.save()
            }
            return existing
        }

        let resolvedName = appleName.isEmpty ? defaultDisplayName(for: appleUserID) : appleName
        let new = Player(
            appleUserID: appleUserID,
            displayName: resolvedName,
            avatarColor: stableAvatarIndex(for: appleUserID)
        )
        context.insert(new)
        try context.save()
        return new
    }

    public static func delete(appleUserID: String, in context: ModelContext) throws {
        var descriptor = FetchDescriptor<Player>(
            predicate: #Predicate { $0.appleUserID == appleUserID }
        )
        descriptor.fetchLimit = 1
        if let existing = try context.fetch(descriptor).first {
            context.delete(existing)
            try context.save()
        }
    }

    // MARK: - Helpers (CoreModels.Player'a delege — tek kaynak)

    static func defaultDisplayName(for appleUserID: String) -> String {
        Player.autoName(for: appleUserID)
    }

    static func isAutoGenerated(_ name: String) -> Bool {
        Player.isAutoGeneratedName(name)
    }

    static func stableAvatarIndex(for appleUserID: String) -> Int {
        Player.stableHash(appleUserID) % 8
    }
}
