import Foundation
import SwiftData

@Model
public final class Player {
    public var appleUserID: String = ""
    public var displayName: String = ""
    public var avatarColor: Int = 0
    public var createdAt: Date = Date()

    // Inverse relationships for CloudKit-compatibility (Match.host / Match.guest)
    @Relationship(inverse: \Match.host)
    public var hostedMatches: [Match]? = nil

    @Relationship(inverse: \Match.guest)
    public var guestedMatches: [Match]? = nil

    public init(
        appleUserID: String,
        displayName: String,
        avatarColor: Int = 0,
        createdAt: Date = .now
    ) {
        self.appleUserID = appleUserID
        self.displayName = displayName
        self.avatarColor = avatarColor
        self.createdAt = createdAt
    }
}

public extension Player {
    /// Otomatik üretilen görünen adların ön eki (`Player-1234`).
    static let autoNamePrefix = "Player-"

    /// Apple isim vermediğinde atanan ad: `Player-XXXX` (kimliğe bağlı sabit
    /// 4 hane). Aynı kullanıcı her cihazda aynı placeholder'ı görür.
    static func autoName(for appleUserID: String) -> String {
        autoNamePrefix + String(format: "%04d", stableHash(appleUserID) % 10000)
    }

    /// Verilen adın otomatik placeholder olup olmadığı (`Player-1234` kalıbı).
    /// Kullanıcının elle/Apple'dan gelen gerçek adını ayırt etmek için kullanılır.
    static func isAutoGeneratedName(_ name: String) -> Bool {
        guard name.hasPrefix(autoNamePrefix) else { return false }
        let suffix = name.dropFirst(autoNamePrefix.count)
        return suffix.count == 4 && suffix.allSatisfy(\.isNumber)
    }

    /// `name` gerçek bir ad mı (boş değil ve placeholder değil)?
    static func isRealName(_ name: String) -> Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.isEmpty && !isAutoGeneratedName(trimmed)
    }

    /// Deterministik djb2 hash — avatar rengi ve placeholder adı için.
    static func stableHash(_ string: String) -> Int {
        var hash = 5381
        for byte in string.utf8 {
            hash = ((hash << 5) &+ hash) &+ Int(byte)
        }
        return abs(hash)
    }
}

